### ISSUE TITLE
More comprehensive GitHub Stats

### ISSUE THREAD

**Issue by nitindermohan** [MPK1/quic-explorer#2]
It would be a good idea to add support for few fields in the GitHub Live Stats

- "last commit": how actively is the implementation updated
- "number of contributors": same as above

**Comment by MPK1** [comment]
I added the two metrics and made the github stats easier extensible by introducing a component in the following commit: https://github.com/MPK1/quic-explorer/commit/b0187b4575d958e8f99725e8ea00bc1a0429ae5e.
